Homework 2 completed
nechepurenkoN/NikitaNechepurenko pull request #2
Opened 2021-06-16 16:50 UTC by nechepurenkoN

## Test running
In order to run tests call
```
mvn test
```
It will run all hw2 tests by default.

## Changing a browser
You can choose any browser that is supported by `WebDriverManager` library.
Just change the name of browser in `seleniumConfig.xml`

```
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
  <entry key="browser">Chrome</entry>
</properties>
```

## Disclaimer
These tests are bad structured due to requirement "not to use patterns and any other magic".
So in the next homework (hw3) I will refactor this code.

2021-06-17 10:23 UTC, shoggy requested changes

2021-06-17 10:23 UTC, shoggy commented on pom.xml
> +    <java.version>1.11</java.version>
starting Java 9 we can use the simplified notation `11` instead of `1.8`
\+ let's try to use `release` instead of `source/target` parameters of `maven-compiler-plugin`

2021-06-17 10:23 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/GeneralItemPlacementTest.java
> +                 });
Usage of loops (and loop like constructions) usually is not a good idea
You have the assertJ in pom.xml, so I suggest to use its methods like `org.assertj.core.api.AbstractIterableAssert#allMatch()` and methods for collections equality  check 

\+ same for other places with loops and forEach with assertions inside

You can chat in private for discussion

2021-06-17 10:23 UTC, shoggy commented on src/test/java/ru/training/at/hw2/BaseJdiTestingIndexPageTest.java
> +    protected SoftAssert assertAccumulator;
SoftAssert is part of a test method, not a test class. Because some tests may need it, some may not.
Please put it to the appropriate place

2021-06-17 10:23 UTC, shoggy commented on src/test/java/ru/training/at/hw2/BaseJdiTestingIndexPageTest.java
> +    }
I suggest splitting actions and assertions into different methods 
Parameterize these methods so no data is hardcoded inside the method (like username, password, SoftAssert instance, expected values, and so on)

\+ same for other methods

2021-06-17 16:08 UTC, nechepurenkoN commented
@shoggy pom settings were fixed. Assertions were separated from actions in 0c4fe2d.

2021-06-18 05:47 UTC, shoggy approved these changes

2021-06-18 06:56 UTC, merged