Homework 3 completed
nechepurenkoN/NikitaNechepurenko pull request #3
Opened 2021-06-25 07:21 UTC by nechepurenkoN

2021-06-25 23:00 UTC, shoggy requested changes
Please fix Compilation Errors

2021-06-25 23:00 UTC, shoggy commented on pom.xml
> +    </dependency>
Duplicated dependencies

2021-06-25 23:00 UTC, shoggy commented on src/main/java/utils/JdiTestingIndexPageData.java
> +    public static final String USERNAME = "Roman Iovlev";
good candidate for externalization, like login/password

2021-06-27 11:24 UTC, nechepurenkoN commented
@shoggy I changed scope of those libs (`testng`, `lombok`, `webdrivermanager`) to default (`compile`) in order to use them in `src` files. I fixed compilation problems after I replaced a file from `hw2`,  now `hw2` package is in a correct state and project compiles without errors.

Also I add User pojo to encapsulate user credentials.

2021-06-28 10:31 UTC, shoggy approved these changes

2021-06-29 05:14 UTC, merged